// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.DAL;

#nullable disable

namespace WebAPI.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240930064300_Start")]
    partial class Start
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("WebAPI.DAL.Entities.Database.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Россия",
                            CreateDate = new DateTime(2024, 9, 30, 13, 43, 0, 665, DateTimeKind.Local).AddTicks(714),
                            Enabled = true,
                            Name = "Завод Жизни",
                            UpdateDate = new DateTime(2024, 9, 30, 13, 43, 0, 665, DateTimeKind.Local).AddTicks(723)
                        },
                        new
                        {
                            Id = 2,
                            Country = "Нидерланды",
                            CreateDate = new DateTime(2024, 9, 30, 13, 43, 0, 665, DateTimeKind.Local).AddTicks(726),
                            Enabled = true,
                            Name = "Завод Сомнений",
                            UpdateDate = new DateTime(2024, 9, 30, 13, 43, 0, 665, DateTimeKind.Local).AddTicks(726)
                        });
                });

            modelBuilder.Entity("WebAPI.DAL.Entities.Database.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Shape")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2024, 9, 30, 13, 43, 0, 665, DateTimeKind.Local).AddTicks(836),
                            Dosage = "Только взрослым по 1-2 таблетки в день.",
                            Enabled = true,
                            ExpirationDate = new DateTime(2024, 10, 3, 13, 43, 0, 665, DateTimeKind.Local).AddTicks(839),
                            ManufacturerId = 1,
                            Name = "Хорошоцин",
                            ReleaseDate = new DateTime(2024, 9, 30, 13, 43, 0, 665, DateTimeKind.Local).AddTicks(839),
                            Shape = 1,
                            UpdateDate = new DateTime(2024, 9, 30, 13, 43, 0, 665, DateTimeKind.Local).AddTicks(836)
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2024, 9, 30, 13, 43, 0, 665, DateTimeKind.Local).AddTicks(844),
                            Dosage = "Пей и пожалей.",
                            Enabled = true,
                            ExpirationDate = new DateTime(2024, 9, 29, 13, 43, 0, 665, DateTimeKind.Local).AddTicks(846),
                            ManufacturerId = 2,
                            Name = "Плохоцин",
                            ReleaseDate = new DateTime(2024, 9, 28, 13, 43, 0, 665, DateTimeKind.Local).AddTicks(846),
                            Shape = 3,
                            UpdateDate = new DateTime(2024, 9, 30, 13, 43, 0, 665, DateTimeKind.Local).AddTicks(845)
                        });
                });

            modelBuilder.Entity("WebAPI.DAL.Entities.Database.Product", b =>
                {
                    b.HasOne("WebAPI.DAL.Entities.Database.Manufacturer", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Manufacturer");
                });
#pragma warning restore 612, 618
        }
    }
}
